"""In-app notification inbox — new saved-search matches and follow-up reminders.

Offline by design: notifications are generated by an opt-in *local* sweep (see
``alerts.py``) and surfaced via a bell in the UI. Nothing is ever emailed or pushed
anywhere — the app performs no outbound delivery (see the no-auto-submit security
invariant). A notification is just a small record the user reads and dismisses.
"""
from __future__ import annotations

import secrets
import time
from dataclasses import dataclass, field, asdict, fields

_MAX_JOBS = 12   # bound the job snapshot list stored on a new-matches notification


@dataclass
class Notification:
    kind: str                                    # "new_matches" | "reminder"
    title: str
    body: str = ""
    ref_id: str = ""                             # saved-search id (new_matches) | application id (reminder)
    count: int = 0                               # number of new matches (new_matches)
    jobs: list = field(default_factory=list)     # bounded job-snapshot dicts (new_matches)
    dedupe: str = ""                             # stable key so a sweep can't duplicate an open item
    read: bool = False
    created: float = 0.0
    id: str = field(default_factory=lambda: secrets.token_urlsafe(8))

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "Notification":
        allowed = {f.name for f in fields(cls)}
        return cls(**{k: v for k, v in d.items() if k in allowed})


_JOB_FIELDS = ("title", "company", "location", "url", "source", "posted", "score")


def new_matches_notification(search, new_jobs: list[dict], now: float | None = None) -> Notification:
    """A 'N new matches for <saved search>' inbox item, carrying a bounded job snapshot."""
    now = now if now is not None else time.time()
    jobs = [{k: j.get(k, "") for k in _JOB_FIELDS} for j in new_jobs[:_MAX_JOBS] if isinstance(j, dict)]
    n = len(new_jobs)
    return Notification(
        kind="new_matches",
        title=search.name,
        ref_id=search.id,
        count=n,
        jobs=jobs,
        dedupe=f"new:{search.id}:{now:.0f}",     # each batch is its own item (history kept)
        created=now,
        body=f"{n} new match{'es' if n != 1 else ''} for “{search.name}”.",
    )


def reminder_notification(nudge: dict, now: float | None = None) -> Notification:
    """A follow-up reminder built from an insights nudge. The dedupe key is stable per
    application, so re-running the sweep refreshes (not duplicates) an open reminder."""
    now = now if now is not None else time.time()
    title = nudge.get("title") or "Application"
    company = nudge.get("company") or ""
    head = title + (f" · {company}" if company else "")
    return Notification(
        kind="reminder",
        title=title,
        ref_id=nudge.get("id", ""),
        dedupe=f"reminder:{nudge.get('id', '')}",
        created=now,
        body=f"{head} — {nudge.get('message', '')}",
    )
